-- Create the drivers table
create table public.drivers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  surname text not null,
  given_names text not null,
  dob text not null,
  id_number text not null unique,
  license_number text not null unique,
  issue_date text not null,
  expiry_date text not null,
  codes text[] not null default '{}',
  vehicle_restrictions text,
  profile_image_url text
);

-- Enable Row Level Security (RLS)
alter table public.drivers enable row level security;

create policy "Enable read access for all users" 
on public.drivers 
for select 
using (true);

create policy "Enable insert for authenticated/anon users" 
on public.drivers 
for insert 
with check (true);

-- Create codes reference table
create table public.codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  description text not null,
  vehicle_types text[]
);

alter table public.codes enable row level security;
create policy "Enable read access for codes" on public.codes for select using (true);

-- Insert reference codes
insert into public.codes (code, description) values
('B', 'Light Motor Vehicles'),
('C', 'Heavy Motor Vehicles'),
('D', 'Public Service Vehicles'),
('A', 'Motorcycles');

-- Optional: Insert a test driver (Use the ID from your sample if you want)
insert into public.drivers (
  surname, given_names, dob, id_number, license_number, issue_date, expiry_date, codes
) values (
  'NEMAUNGA', 'DESMOND LINCOLN', '15/05/1985', '50152916N50', 'AA00033205', '01/01/2023', '01/01/2028', ARRAY['2', '4']
);
