-- DANGEROUS: Wipes existing tables to start fresh
drop table if exists public.drivers cascade;
drop table if exists public.codes cascade;

-- 1. Create 'codes' table (Reference)
create table public.codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  description text not null,
  vehicle_types text[] -- e.g. {'Light', 'Heavy'}
);
alter table public.codes enable row level security;
create policy "Public Read Codes" on public.codes for select using (true);

-- Insert standard Zim license codes
insert into public.codes (code, description, vehicle_types) values
('A', 'Motorcycles', ARRAY['Motorcycle']),
('B', 'Light Motor Vehicles', ARRAY['Light Vehicle']),
('C', 'Heavy Motor Vehicles', ARRAY['Truck', 'Bus']),
('D', 'Public Service Vehicles', ARRAY['Bus', 'Taxi']),
('E', 'Heavy OmniBus', ARRAY['Bus']);

-- 2. Create 'drivers' table
create table public.drivers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  
  -- Personal Info
  surname text not null,
  given_names text not null,
  dob text not null, -- Storing as dd/MM/yyyy text for simplicity, or use DATE type
  id_number text not null unique,
  
  -- License Info
  license_number text not null unique,
  issue_date text not null,
  expiry_date text not null,
  codes text[] not null default '{}', -- Array of codes e.g. ['B', 'C']
  
  -- Media
  profile_image_url text
);

alter table public.drivers enable row level security;

-- Policies (Adjust strictness as needed)
create policy "Public Read Drivers" on public.drivers for select using (true);
create policy "Public Insert Drivers" on public.drivers for insert with check (true);

-- 3. Storage Bucket Setup (Script cannot create bucket directly usually, do via UI)
-- But we can set policies if the bucket 'driver_photos' exists.
-- Please create a Public bucket named 'driver_photos' in Supabase Storage.

-- Policy: Allow public read of photos
-- create policy "Public Access"
-- on storage.objects for select
-- using ( bucket_id = 'driver_photos' );

-- Policy: Allow inserts (uploads)
-- create policy "Public Upload"
-- on storage.objects for insert
-- with check ( bucket_id = 'driver_photos' );

-- 4. Audit Logs Table
-- Run this in the Supabase SQL Editor to enable auditing.
create table if not exists public.audit_logs (
  id          bigint generated by default as identity primary key,
  created_at  timestamp with time zone default now() not null,
  action      text not null,                          -- e.g. VERIFY_LICENSE, REGISTER_DRIVER
  performed_by uuid references public.profiles(id),  -- null = system / unauthenticated
  target_entity_id text,                              -- driver id or user id acted upon
  details     jsonb                                   -- free-form context (status, method, etc.)
);

alter table public.audit_logs enable row level security;

-- Admins / authenticated users can insert audit logs
create policy "Auth Insert Audit Logs"
  on public.audit_logs for insert
  with check (auth.role() = 'authenticated');

-- Only admins can read audit logs (adjust role check to match your profile roles)
create policy "Auth Read Audit Logs"
  on public.audit_logs for select
  using (auth.role() = 'authenticated');

-- Index for fast time-based queries on the dashboard
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);
create index if not exists audit_logs_action_idx on public.audit_logs (action);
