-- DANGEROUS: Wipes existing tables to start fresh
drop table if exists public.drivers cascade;
drop table if exists public.codes cascade;

-- 1. Create 'codes' table (Reference)
create table public.codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  description text not null,
  vehicle_types text[] -- e.g. {'Light', 'Heavy'}
);
alter table public.codes enable row level security;
create policy "Public Read Codes" on public.codes for select using (true);

-- Insert standard Zim license codes
insert into public.codes (code, description, vehicle_types) values
('A', 'Motorcycles', ARRAY['Motorcycle']),
('B', 'Light Motor Vehicles', ARRAY['Light Vehicle']),
('C', 'Heavy Motor Vehicles', ARRAY['Truck', 'Bus']),
('D', 'Public Service Vehicles', ARRAY['Bus', 'Taxi']),
('E', 'Heavy OmniBus', ARRAY['Bus']);

-- 2. Create 'drivers' table
create table public.drivers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Personal Info
  surname text not null,
  given_names text not null,
  dob text not null, -- Storing as dd/MM/yyyy text for simplicity, or use DATE type
  id_number text not null unique,
  
  -- License Info
  license_number text not null unique,
  issue_date text not null,
  expiry_date text not null,
  codes text[] not null default '{}', -- Array of codes e.g. ['B', 'C']
  vehicle_restrictions text,
  
  -- Media
  profile_image_url text
);

alter table public.drivers enable row level security;

-- Policies (Adjust strictness as needed)
create policy "Public Read Drivers" on public.drivers for select using (true);
create policy "Public Insert Drivers" on public.drivers for insert with check (true);

-- 3. Storage Bucket Setup (Script cannot create bucket directly usually, do via UI)
-- But we can set policies if the bucket 'driver_photos' exists.
-- Please create a Public bucket named 'driver_photos' in Supabase Storage.

-- Policy: Allow public read of photos
-- create policy "Public Access"
-- on storage.objects for select
-- using ( bucket_id = 'driver_photos' );

-- Policy: Allow inserts (uploads)
-- create policy "Public Upload"
-- on storage.objects for insert
-- with check ( bucket_id = 'driver_photos' );
